# Generated by Django 3.2.5 on 2021-07-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0002_auto_20210724_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='neighbor_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(default='location', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(default='name', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_count',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='population',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
