# Generated by Django 3.2.5 on 2021-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='hospital_caunt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
