# Generated by Django 3.2.5 on 2021-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0006_neighborhood_hospital_caunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hospital_caunt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
