# Generated by Django 3.2.5 on 2021-07-24 14:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0007_auto_20210724_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='hospital_caunt',
            new_name='hospital_count',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image path', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
