# Generated by Django 3.2.5 on 2021-07-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0008_auto_20210724_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2004-10-19 10:23:54+02'),
            preserve_default=False,
        ),
    ]
