# Generated by Django 3.2.5 on 2021-07-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0009_neighborhood_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbor_app.profile'),
        ),
    ]
