# Generated by Django 3.2.5 on 2021-07-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0015_auto_20210726_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='hospital_count',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='police_count',
        ),
    ]
