# Generated by Django 3.2.5 on 2021-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0016_auto_20210726_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2004-10-19 10:23:54+02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='hospital_contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
