# Generated by Django 3.2.5 on 2021-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0017_auto_20210726_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hospital_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
